#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/spring_crud?useSSl=false
#    username: root
#    password:
#
##jpa setting
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    database-platform: org.hibernate.dialect.MySQLDialect
#
#
#
